name: dfa_media
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  talker: ^4.1.3
  talker_dio_logger: ^4.1.3
  talker_flutter: ^4.1.3
  talker_bloc_logger: ^4.1.3
  bloc: ^8.1.4
  dartz: ^0.10.1
  flutter_bloc: ^8.1.5
  flutter_svg: ^2.0.10+1
  smooth_page_indicator: ^1.2.0
  json_annotation: ^4.8.1
  dio: ^5.5.0+1
  flutter_dotenv: ^5.1.0
  skeletonizer: ^1.4.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner:
  json_serializable: ^6.8.0
  flutter_gen_runner: ^5.6.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
    - .env


  fonts:
    - family: Stolzl
      fonts:
        - asset: fonts/stolzl_light.otf
          weight: 300
        - asset: fonts/stolzl_thin.otf
        - asset: fonts/stolzl_regular.otf
          weight: 400
        - asset: fonts/stolzl_medium.otf
          weight: 500
        - asset: fonts/stolzl_bold.otf
          weight: 700

flutter_gen:
  output: lib/gen/
  line_length: 80

  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true
